In [1]:
import numpy as np

stock1 = np.array([[100,105,98],
                   [102,108,101],
                   [104,110,103],
                   [106,112,105],
                   [108,115,107]])

stock2 = np.array([[95,100,90],
                   [97,102,92],
                   [99,104,95],
                   [101,106,97],
                   [103,108,99]])

sum_matrix = stock1 + stock2
diff_matrix = stock1 - stock2

print("Element-wise Sum:")
print(sum_matrix)

print("Element-wise Difference:")
print(diff_matrix)

Element-wise Sum:
[[195 205 188]
 [199 210 193]
 [203 214 198]
 [207 218 202]
 [211 223 206]]
Element-wise Difference:
[[5 5 8]
 [5 6 9]
 [5 6 8]
 [5 6 8]
 [5 7 8]]
